apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordapp
spec:
  selector:
    matchLabels:
      app: wordapp
  template:
    metadata:
      labels:
        app: wordapp
    spec:
      containers:
      - name: wordapp
        image: maahin/wordapp:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 4000
        env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: wordapp-config
              key: DB_URL
        - name: API_KEY
          valueFrom:
            secretKeyRef: 
              name: wordapp-secret
              key: API_KEY
        - name: API_HOST
          valueFrom:
            configMapKeyRef:
              name: wordapp-config
              key: API_HOST
---
apiVersion: v1
kind: Service
metadata:
  name: wordapp-service
spec:
  selector:
    app: wordapp
  type: NodePort
  ports:
  - name: wordapp-service-port
    port: 4000
    targetPort: 4000
    nodePort: 30000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: wordapp-monitor
  labels:
    release: kube-prom-stack
    app: wordapp
spec:
  endpoints:    
  - path: /metrics
    port: wordapp-service-port
    targetPort: 4000
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: wordapp
