apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alert-manager-config
  namespace: monitoring
spec:
  route:
    receiver: 'slack'
    repeatInterval: 10m
    routes:
    - matchers:
      - name: alertname
        value: K8s_pod_crash_looping
      repeatInterval: 5m
    - matchers:
      - name: alertname
        value: host_medium_cpu_load
    - matchers:
      - name: alertname
        value: host_high_cpu_load
      repeatInterval: 10m
  receivers:
  - name: 'slack'
    slackConfigs:
    - apiURL:
        name: secret-webhookurl
        key: url
      color: '{{ if eq .Status "firing" }}danger{{ else }}good{{ end }}'
      title: '[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] Prometheus Event Notification'
      pretext: '{{ .CommonAnnotations.summary }}'
      text: |-
        {{ range .Alerts }}
          {{- if or .Annotations.summary .Annotations.description }}*Alert:* {{ .Annotations.summary }}{{ .Annotations.description }} - `{{ .Labels.severity }}`{{- end }}
          {{ if .Annotations.message }}*Message:* {{ .Annotations.message }}{{ end }}
          {{ if or .Annotations.graph .Annotations.graphUrl }}*Graph:* <{{ .Annotations.graph }}{{ .Annotations.graphUrl }}|:chart_with_upwards_trend:>{{ end }}{{ if or .Annotations.grafana .Annotations.grafanaUrl }}*Grafana:* <{{ .Annotations.grafana }}{{ .Annotations.grafanaUrl }}|:bar_chart:>{{ end }} {{ if or .Annotations.runbook .Annotations.runbook_url }} *Runbook:* <{{ .Annotations.runbook }}{{ .Annotations.runbook_url }}|:spiral_note_pad:>{{ end }}
          *Details:*
          {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
          {{ end }}
        {{ end }}
      sendResolved: true
      